- README.md
se actualice el README con detalles de `nvm`
1. README actualizado con nvm
2. ...
3. ...
> actualizo readme con comando para nvm

- src/app/about-cetav/page.js
- src/app/components/MainContent.jsx
- src/app/contacto/page.js
- src/app/cursos-libres/page.js
- src/app/egresados/page.js
- src/app/layout.js
- src/app/page.js
- src/app/preguntas-frecuentes/page.js
- src/app/tecnicos/analisis-y-visuali-de-datos/page.js
- src/app/tecnicos/animacion-3d/page.js
- src/app/tecnicos/ciberseguridad/page.js
- src/app/tecnicos/dis-y-des-web/page.js
- src/app/tecnicos/merc-digital-y-diseno/page.js
- src/app/tecnicos/motion-graphics/page.js
- src/app/tecnicos/page.js
- src/app/tecnicos/paid-media/page.js
- src/app/tecnicos/post-produc-audiovisual/page.js
Agrego `MainContent` component y se actualice el layout, y pages, ahora todas las secciones tienen un contenedor con un max-width de 1180px; adicionalmente, se reemplazan elementos de HTML por componentes de Chakra
1. Titulos de cada seccion debe usar un Chakra components
2. Todas las secciones tienen un wrapper con un max-width de 1180px
**Sin el wrapper**
**Con el wrapper**
> Se agrega main wrapper y se reemplaza html h1

- src/app/components/OurTeachers.jsx
- src/app/content/teachers.js
- src/app/tecnicos/analisis-y-visuali-de-datos/page.js
- src/app/tecnicos/animacion-3d/page.js
- src/app/tecnicos/ciberseguridad/page.js
- src/app/tecnicos/dis-y-des-web/page.js
- src/app/tecnicos/merc-digital-y-diseno/page.js
- src/app/tecnicos/motion-graphics/page.js
- src/app/tecnicos/paid-media/page.js
- src/app/tecnicos/post-produc-audiovisual/page.js
Issues https://github.com/cetav-ddw/lalibertad-cetav/issues/48 https://github.com/cetav-ddw/lalibertad-cetav/issues/51
Se agrega componente de profesores, recibe los datos por prop, hay que actualizar el config con datos nuevos.
1. En cada pagina de tecnico se carga el componente de nuestros profesores, los datos vienen de un config
> Our teachers

- src/app/components/ExpectactionsBanner.jsx
- src/app/tecnicos/analisis-y-visuali-de-datos/page.js
- src/app/tecnicos/animacion-3d/page.js
- src/app/tecnicos/ciberseguridad/page.js
- src/app/tecnicos/dis-y-des-web/page.js
- src/app/tecnicos/merc-digital-y-diseno/page.js
- src/app/tecnicos/motion-graphics/page.js
- src/app/tecnicos/paid-media/page.js
- src/app/tecnicos/post-produc-audiovisual/page.js
Issue https://github.com/cetav-ddw/lalibertad-cetav/issues/49
Banner con expectativas.
Falta agregar los iconos, Ignacio esta agregando el paquete en una historia aparte
1. Mismo componente en cada pagina del tecnico
2. ...
3. ...
> Expectactions banner

- src/app/preguntas-frecuentes/page.js
Solo estan escritas las preguntas, las respuestas se actualizaran en otro branch. Entre Jason Aguilar y mi persona. 
1. ... 
2. ...
3. ...
> Preguntas base FAQ

- src/app/preguntas-frecuentes/page.js
Agregue respuestas de las FAQ. De los campos "Sobre el CETAV", "Financiamiento" e "Inserción Laboral". 
Faltaría solamente las respuestas de "Proceso de admisión", que se encarga de ellos el compañero Jason Aguilar. 
1. Cambie los lorem ipsum de "Sobre el CETAV", "Financiamiento" e "Inserción Laboral".  Por las respuestas que están en la pagina actual del CETAV. 
2. Deje solamente el lorem ipsum de las 4 preguntas de "Proceso de admisión".
> Faq respuestas m

- src/app/preguntas-frecuentes/page.js
Cambie todos los h2 de la page por h3, ya que los titulos estan en h2.
1. Todos los h2 se cambiaron por h3.
> Cambio de h2 a h3

- src/app/components/GoodToKnowBanner.jsx
- src/app/content/pre-inscription.js
- src/app/tecnicos/analisis-y-visuali-de-datos/page.js
- src/app/tecnicos/animacion-3d/page.js
- src/app/tecnicos/ciberseguridad/page.js
- src/app/tecnicos/dis-y-des-web/page.js
- src/app/tecnicos/merc-digital-y-diseno/page.js
- src/app/tecnicos/motion-graphics/page.js
- src/app/tecnicos/paid-media/page.js
- src/app/tecnicos/post-produc-audiovisual/page.js
Issue https://github.com/cetav-ddw/lalibertad-cetav/issues/46
Agrego contenido dummy y componente para la seccion de que saber antes.
Falta agregar icono.
1. Mismo componente en cada pagina de tecnico
2. ...
3. ...
> Contenido y componente para banner de que saber antes

- src/app/about-cetav/page.js
- src/app/acerca/page.js
- src/app/components/ExpectactionsBanner.jsx
- src/app/components/FaqsBanner.jsx
- src/app/components/Footer.jsx
- src/app/components/GoodToKnowBanner.jsx
- src/app/components/InscriptionBanner.jsx
- src/app/components/LaboralFormation.jsx
- src/app/components/MainContent.jsx
- src/app/components/OurTeachers.jsx
- src/app/components/SectionHeading.jsx
- src/app/components/Testimonies/TestimonyList.jsx
- src/app/components/navigation.jsx
- src/app/contacto/page.js
- src/app/cursos-libres/page.js
- src/app/egresados/page.js
- src/app/page.js
- src/app/preguntas-frecuentes/page.js
- src/app/tecnicos/analisis-y-visuali-de-datos/page.js
- src/app/tecnicos/animacion-3d/page.js
- src/app/tecnicos/ciberseguridad/page.js
- src/app/tecnicos/dis-y-des-web/page.js
- src/app/tecnicos/merc-digital-y-diseno/page.js
- src/app/tecnicos/motion-graphics/page.js
- src/app/tecnicos/page.js
- src/app/tecnicos/paid-media/page.js
- src/app/tecnicos/post-produc-audiovisual/page.js
Actualizar y normalizar espaciado entre componentes, ajustar tamaño de fuentes.
- distancia entre componentes, espaciado vertical dado con margin bottom, 16 (size de chakra)
- se remueven los valores en px, y se usa los valores de chakra
https://github.com/cetav-ddw/lalibertad-cetav/assets/598867/73edaee2-b9a5-4060-87c6-e332f8943ee2
1. No cambios en funcionalidad
2. ...
3. ...
> Round 1 actualizando sizes

- src/app/components/ExpectactionsBanner.jsx
- src/app/components/SoftSkillsBanner.jsx
- src/app/tecnicos/analisis-y-visuali-de-datos/page.js
- src/app/tecnicos/animacion-3d/page.js
- src/app/tecnicos/ciberseguridad/page.js
- src/app/tecnicos/dis-y-des-web/page.js
- src/app/tecnicos/merc-digital-y-diseno/page.js
- src/app/tecnicos/motion-graphics/page.js
- src/app/tecnicos/paid-media/page.js
- src/app/tecnicos/post-produc-audiovisual/page.js
Issue https://github.com/cetav-ddw/lalibertad-cetav/issues/50
Banner de soft skills / 4to eje. Se agrega a cada pagina de tecnicos
1. ...
2. ...
3. ...
> Banner de softskills

- src/app/components/Footer.jsx
Actualizo estilos del footer
1. ...
2. ...
3. ...
> Agrego estilos para footer

- src/app/components/Header.jsx
- src/app/components/MainNavigation.jsx
> fix deployment

- src/app/egresados/components/YearbookCards.jsx
- src/app/egresados/page.js
-Se agrega el título en la sección de anuarios y también un cambio en los links, utilizando "isExternal" y "ExternalLinkIcon".
1. ...
2. ...
3. ...
> Titulo y Links

- src/app/page.js
> Actualizo home header

- src/app/components/ContactDetail.jsx
- src/app/components/LocationMap.jsx
Se agregaron media querries para hacer la pagina de contacto responsive
1. Revisar que se vea de manera correcta la pagina de contacto en los diferentes viewports
> responsive contacto

- src/app/components/VideoModal.jsx
> actualizo video cetav

- src/app/components/MainContent.jsx
- src/app/components/MainNavigation.jsx
- src/app/components/PageHeading.jsx
> Ajustes padding y formato

- src/app/components/LaboralFormation.jsx
> Arreglo de formato y espaciado en la seccion "Formación que abre puertas laborales"

- src/app/components/GoodToKnowBanner.jsx
- src/app/components/OurTeachers.jsx
- src/app/components/SoftSkillsBanner.jsx
> Arreglo de formato y espaciado en componentes de las paginas de técnicos

- src/app/components/AdvisoryBoard.jsx
- src/app/components/CetavIntro.jsx
> Arreglo de formato y espaciado en la seccion "consejo asesor" y "cetav"
